name: Docker Build

on:
  push:
    branches: [ S2-3.1/grpc_docker ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: Backend
    - name: Create config file
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: |
        echo $FIREBASE_CONFIG > ./firebaseConfig.json
    - name: Clone honeypot
      run: |
        cd ..
        git clone https://github.com/Honeybrain/Honeypot
        cd Honeypot
    - name: Build protos
      run: |
        cd ../Honeypot
        ./scripts/make_backend_protos.sh ./protos ../Backend
    - name: Build the Docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        docker build -t $DOCKER_USER/hb_dashboard_back .
    - name: Push the Docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker push $DOCKER_USER/hb_dashboard_back